# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
print (np.__version__)

1.20.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [69]:
# Method 1
a = np.random.random((2,3,5))


In [70]:
# Method 2
a = np.random.rand(2,3,5)

In [71]:
# Method 
a = a.reshape(2,3,5)


#### 4. Print *a*.


In [72]:
# your code here
a

array([[[0.88089126, 0.29902219, 0.52934115, 0.89573942, 0.60994585],
        [0.4856618 , 0.73325741, 0.92357332, 0.84902241, 0.30295529],
        [0.53876793, 0.07217593, 0.56275433, 0.219604  , 0.83892135]],

       [[0.13780458, 0.30697312, 0.2776265 , 0.37911246, 0.12404097],
        [0.85508525, 0.27461333, 0.34418595, 0.77282533, 0.60407415],
        [0.25688954, 0.21083325, 0.67646287, 0.79357829, 0.58036367]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [73]:
# your code here
b = np.ones((5,2,3))


#### 6. Print *b*.


In [74]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [75]:
# your code here
print (a.size)
print (b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [76]:
# your answer here
a1= np.array ([[1,1,1],[3,3,3]])
a2= np.array ([[4,4,4],[3,3,3]])
a1+a2

a+b

#it`s impossible add a + b  because they have differents dimensions



ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [85]:
# your code here


c= np.transpose(b).reshape(2,3,5)
c


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [89]:
# your code/answer here
d = np.add(a,c)
d

# because I convert the same strcuture (2,3,5)

array([[[1.88089126, 1.29902219, 1.52934115, 1.89573942, 1.60994585],
        [1.4856618 , 1.73325741, 1.92357332, 1.84902241, 1.30295529],
        [1.53876793, 1.07217593, 1.56275433, 1.219604  , 1.83892135]],

       [[1.13780458, 1.30697312, 1.2776265 , 1.37911246, 1.12404097],
        [1.85508525, 1.27461333, 1.34418595, 1.77282533, 1.60407415],
        [1.25688954, 1.21083325, 1.67646287, 1.79357829, 1.58036367]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [96]:
# your code/answer here
print (a)
print(a.dtype)
print (d)
print(d.dtype)

[[[0.88089126 0.29902219 0.52934115 0.89573942 0.60994585]
  [0.4856618  0.73325741 0.92357332 0.84902241 0.30295529]
  [0.53876793 0.07217593 0.56275433 0.219604   0.83892135]]

 [[0.13780458 0.30697312 0.2776265  0.37911246 0.12404097]
  [0.85508525 0.27461333 0.34418595 0.77282533 0.60407415]
  [0.25688954 0.21083325 0.67646287 0.79357829 0.58036367]]]
float64
[[[1.88089126 1.29902219 1.52934115 1.89573942 1.60994585]
  [1.4856618  1.73325741 1.92357332 1.84902241 1.30295529]
  [1.53876793 1.07217593 1.56275433 1.219604   1.83892135]]

 [[1.13780458 1.30697312 1.2776265  1.37911246 1.12404097]
  [1.85508525 1.27461333 1.34418595 1.77282533 1.60407415]
  [1.25688954 1.21083325 1.67646287 1.79357829 1.58036367]]]
float64


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [97]:
# your code here
e = np.multiply (a,c)
e

array([[[0.88089126, 0.29902219, 0.52934115, 0.89573942, 0.60994585],
        [0.4856618 , 0.73325741, 0.92357332, 0.84902241, 0.30295529],
        [0.53876793, 0.07217593, 0.56275433, 0.219604  , 0.83892135]],

       [[0.13780458, 0.30697312, 0.2776265 , 0.37911246, 0.12404097],
        [0.85508525, 0.27461333, 0.34418595, 0.77282533, 0.60407415],
        [0.25688954, 0.21083325, 0.67646287, 0.79357829, 0.58036367]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [98]:
# your code/answer here
print (e.dtype)
print (a.dtype)
print (e.ndim)
print (a.ndim)

float64
float64
3
3


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [102]:
# your code here
d_max = d.max()
d_max

1.9235733202915992

In [104]:
d_min = d.min()
d_min

1.0721759274693805

In [103]:
d_mean = d.mean()
d_mean

1.5112034303658404

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here